language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
  
env:
  - AWS_DEFAULT_REGION=eu-west-1

script: "pyb verify analyze"

after_success:
  - coveralls --verbose

